version: '3.1'

services:

  db:
    image: postgres
    ports:
      - "5429:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: pass
      POSTGRES_DB: simdb